/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;

public class Main {

	public static void main(String[] args) throws IOException {

		ArrayList<Libro> catalogo = new ArrayList<Libro>();
		String elemento = null;
		String isbn = "";
		while (true) {
			int opcion = menu();
			switch (opcion) {
			case 1:
				// TODO Alta de Libro
				// titulo:isbn:genero:autor:paginas
				alta(catalogo);
				break;
			case 2:
				// TODO Lista de Libros
				mostrarLibro(catalogo);
				break;
			case 3:
				// TODO Lista de Libros
				eliminarLibro(catalogo);
				break;
			case 4:
				busquedaLibro(catalogo);
				break;
			case 5:
				ordenaLibro(catalogo);
				break;
			case 6:
				crearFichero(catalogo);
				break;
			default:
				break;
			}
		}
	}

	private static int menu() {
		int opcion = 0;

		do {
			System.out.println("Opciones:");
			System.out.println("1. Alta de Libro");
			System.out.println("2. Lista de Libros");
			System.out.println("3. Baja de Libros");
			System.out.println("4. Busqueda de Libros");
			System.out.println("5. Ordenacion de Libros");
			System.out.println("6. Guardarlo en ficheros");
			System.out.println("7. Vaciar catalogo");
			System.out.println("Introduce la opcion:");

			opcion = leerOpcion(7);

		} while (opcion <= 0);

		return opcion;
	}

	private static int leerOpcion(int max) {
		int opcion = -1;
		try {
			Scanner teclado = new Scanner(System.in);
			opcion = teclado.nextInt();
			if (opcion > max)
				opcion = -1;
		} catch (InputMismatchException e) {
			System.out.println("Opcion incorrecta");
		}

		return opcion;
	}

	private static void alta(ArrayList<Libro> catalogo) {
		// Leer de la entrada
		String datosLibro = obtenerDatosLibro();
		// titulo:isbn:genero:autor:paginas
		// Procesar la entrada
		Libro libro = procesaEntrada(datosLibro);
		// Crear el libro con los datos de la entrada
		catalogo.add(libro);
		// Meter el libro en el catalogo
	}

	private static void mostrarLibro(ArrayList<Libro> catalogo) {

		//Metodo For Each
		
		for (Libro l : catalogo) {
			System.out.println(l);
		}

		//Metodo bucle con size 
		
//		for (int i = 0; i < catalogo.size(); i++) {
//			System.out.println("Libro " + (i + 1));
//			System.out.println("-------------");
//			System.out.println("Titulo: " + catalogo.get(i).getTitulo());
//			System.out.println("ISBN: " + catalogo.get(i).getIsbn());
//			System.out.println("Genero: " + catalogo.get(i).getGenero());
//			System.out.println("Autor: " + catalogo.get(i).getAutor());
//			System.out.println("Paginas: " + catalogo.get(i).getPaginas());
//			System.out.println();

		}

//		troya:1234:novela:javi:1234
//		IT:1234:Novela:King:1234
//  	Marvel:5678:poesia:ironman:232
	

	private static void eliminarLibro(ArrayList<Libro> catalogo) {

		System.out.println("Escribe el titulo del libro que desea eliminar");
		Scanner teclado = new Scanner(System.in);
		int elemento = teclado.nextInt();
		catalogo.remove(elemento);

	}

	private static void busquedaLibro(ArrayList<Libro> catalogo) {
		String isbn = "";
		System.out.println("Escribe el isbn del libro que desea buscar");
		Scanner teclado = new Scanner(System.in);
		isbn = teclado.next();

		Libro l = new Libro();
		l.setIsbn(isbn);

		int posicion = 0;
		posicion = catalogo.indexOf(l);
		if (posicion < 0) {
			System.out.println("El libro no esta agregado en el catalogo");
		} else {
			System.out.println("Libro encontrado");
			System.out.println(catalogo.get(posicion));
		}

	}

	private static void ordenaLibro(ArrayList<Libro> catalogo) {
		// TODO Auto-generated method stub

		
		Collections.sort(catalogo);
		System.out.println("Catalogo ordenado");

		

	}

	private static String obtenerDatosLibro() {
		String datos = null;

		boolean validado = false;
		while (!validado) {
			System.out.println("Introduce los datos de un libro.");
			System.out.println("Usa el formato \"titulo:isbn:genero:autor:paginas\"");
			try {
				datos = leerCadena();
				if (true)// Supongo de momento que valida siempre
					validado = true;
			} catch (InputMismatchException e) {
				System.out.println("Datos de entrada no validos");
			}
		}

		return datos;
	}
	
	private static void crearFichero (ArrayList<Libro> catalogo) throws IOException {
		
		try {
  	      FileWriter escribeFichero = new FileWriter("FicheroCatalogo.txt");
  	      for(Libro l : catalogo) {
  	    	  escribeFichero.write(l.toStringFile());
  	    	  System.out.println("El catágolo se ha guardado en el fichero");
  	      }
  	      escribeFichero.close();
  	    } catch (IOException e) {
  	      System.out.println("Se ha producido un error, vuelva a intentarlo");
  	      e.printStackTrace();
  	    }

		
//		try {
//		      FileWriter myWriter = new FileWriter("ACatalogo.txt");
//		      myWriter.write(catalogo);
//		      myWriter.close();
//		      System.out.println("El catalogo esta escrito en el fichero");
//		    } catch (IOException e) {
//		      System.out.println("accion erronea");
//		      e.printStackTrace();
//		    }
		
		/**
		 * el write solo lo lee a traves de strings, no se puede con arraylist.
		 * hay que crear toString para devolverme un libro en cada cadena. se debe crerar un bucle con for each
		 * for(Libro l :catalogo){
		 * write(l._______());
		 * }
		 */
		
//		 try {
//		      File myObj = new File("ACatalogo.txt");
//		      Scanner myReader = new Scanner(myObj);
//		      while (myReader.hasNextLine()) {
//		        String data = myReader.nextLine();
//		        System.out.println(data);
//		      }
//		      myReader.close();
//		    } catch (FileNotFoundException e) {
//		      System.out.println("An error occurred.");
//		      e.printStackTrace();
//		    }
//		 File myObj = new File("ACatalogo.txt");
//		 if (myObj.exists()) {
//		      System.out.println("File name: " + myObj.getName());
//		      System.out.println("Absolute path: " + myObj.getAbsolutePath());
//		      System.out.println("Writeable: " + myObj.canWrite());
//		      System.out.println("Readable " + myObj.canRead());
//		      System.out.println("File size in bytes " + myObj.length());
//		    } else {
//		      System.out.println("The file does not exist.");
//		    }
		
		
		
//		File archivoCatalogo = new File ("C:\\archivoCatalogo.txt");
//		FileReader fr = new FileReader (archivoCatalogo);
//		BufferedReader br = new BufferedReader(fr);
//		String linea = br.readLine();
		}
	
	private static void vaciarCatalogo(ArrayList<Libro> catalogo) {
		catalogo.clear();
		System.out.println("Catalogo vacio");
	}

	private static Libro procesaEntrada(String entrada) {
		Libro libro = null;

		String[] datos = entrada.split(":");

		String titulo = datos[0];
		String isbn = datos[1];
		Genero genero = Genero.getGenero(datos[2]);
		String autor = datos[3];
		Integer paginas = Integer.parseInt(datos[4]);

		libro = new Libro(titulo, isbn, genero, autor, paginas);

		return libro;
	}

	private static String leerCadena() {
		String opcion = null;
		Scanner teclado = new Scanner(System.in);
		opcion = teclado.nextLine();
		return opcion;
	}
}
